@OpenTelemetryApi_HostAddress = http://localhost:5107

GET {{OpenTelemetryApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{OpenTelemetryApi_HostAddress}}/users
Accept: application/json